kind: Secret
apiVersion: v1
metadata:
  name: google-maps-secret
  labels:
    application: kraken-twitter
  annotations:
    template.openshift.io/expose-api_key: '{.data[''api-key'']}'
stringData:
  api-key: "{{ google_maps_api_key }}"
