kind: Secret
apiVersion: v1
metadata:
  name: twitter-secret
  labels:
    application: kraken-twitter
  annotations:
    template.openshift.io/expose-api_key: '{.data[''api-key'']}'
    template.openshift.io/expose-api_secret: '{.data[''api-secret'']}'
    template.openshift.io/expose-access_token: '{.data[''access-token'']}'
    template.openshift.io/expose-access_secret: '{.data["access-secret"]}'
stringData:
  api-key: "{{ twitter_api_key }}"
  api-secret: "{{ twitter_api_secret }}"
  access-token: "{{ twitter_access_token }}"
  access-secret: "{{ twitter_access_secret }}"
