
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: CheCluster.v1.org.eclipse.che
  name: "{{ proj_nm_infra }}-crw"
  namespace: "{{ proj_nm_infra }}"
spec:
  targetNamespaces:
  - "{{ proj_nm_infra }}"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: codeready-workspaces
  namespace: "{{ proj_nm_infra }}"
spec:
  channel: latest
  installPlanApproval: Automatic
  name: codeready-workspaces
  source: redhat-operators
  sourceNamespace: openshift-marketplace
